spring:
  application:
    name: sd-corporate-loan

server:
  port: 8080
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      probes:
        enabled: true   # /actuator/health/liveness + /readiness for K8s probes
  info:
    env:
      enabled: true

info:
  bian:
    serviceDomain: "Corporate Loan"
    businessArea: "Operations and Execution"
    businessDomain: "Loans and Deposits"
    functionalPattern: "Fulfill"
    assetType: "Corporate Loan Facility"
    controlRecord: "Corporate Loan Facility Fulfillment Arrangement"

resilience4j:
  circuitbreaker:
    instances:
      serviceDomain:
        slidingWindowSize: 20
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
